version: "3"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=pokeapi
      - POSTGRES_USER=pokeapi-user
      - POSTGRES_PASSWORD=pokeapi-password
    ports:
      - "5432:5432"
    networks:
      - bridgenetwork

  django:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: pokeapi_local_django
    container_name: pokeapi_local_django
    depends_on:
      - postgres
    environment:
      - DJANGO_DATABASE_URL=psql://pokeapi-user:pokeapi-password@postgres:5432/pokeapi
      - POKEAPI_API_URL=https://beta.pokeapi.co/graphql/v1beta
      - DJANGO_DEBUG=True
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - POSTGRES_DB=pokeapi
      - POSTGRES_USER=pokeapi-user
      - POSTGRES_PASSWORD=pokeapi-password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    networks:
      - bridgenetwork
    volumes:
      - .:/app:z

networks:
  bridgenetwork:
    driver: bridge
